In [1]:
from universal_tester import *

In [2]:
from C2D_Models import *
from C3D_Models import *
from ConvLSTM_AE.ConvLSTM_AE import *
from PatchWise.models_PatchWise import *

In [3]:
test_model(
    dataset_type = "ucsd2",
    model = C2D_AE_128_3x3(channels = 1),
    model_path = '../../VAD_MODEL_TREE/UCSD2/C2D/C2D_AE_128_3X3|_ADAM_MSE_UCSD2_NORMAL/C2D_AE_128_3X3|_ADAM_MSE_UCSD2_NORMAL.pth.tar',
    tester_kwargs = {
        "save_vis": False,
        "regularity_type": "savgol", # normalized_regularity
        "stackFrames": 64,
        "recordResults": False,
        "forceNormalTest": False,
        "filename_addon": "dummy",
        "setEval": True, 
        "useGPU": True
    },
    dataset_kwargs={'image_size': 128, 'image_type': 'normal'},
    return_results=True
)

../general/data.py:489: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  temporal_labels = np.array(temporal_labels)
12it [00:01,  6.91it/s]


----------------------------------------


12it [00:11,  1.04it/s]
/home/ambreesh/Documents/amb_venv/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


OrderedDict([('auc_roc_score_agg_absolute', 0.87480555704554), ('auc_roc_score_agg_psnr', 0.8392007053585796), ('auc_roc_score_agg_squared', 0.8338987823848093), ('auc_roc_score_agg_ssim', 0.8477243469398703), ('auc_roc_score_mean_absolute', 0.9300368415087243), ('auc_roc_score_mean_psnr', 0.8775900983761078), ('auc_roc_score_mean_squared', 0.8794511823763411), ('auc_roc_score_mean_ssim', 0.9016395135763785), ('auc_roc_score_overall_absolute', 0.6997130290189346), ('auc_roc_score_overall_psnr', 0.743628640776699), ('auc_roc_score_overall_squared', 0.7421300890414633), ('auc_roc_score_overall_ssim', 0.7342719117094888), ('eer_agg_absolute', 0.21966019417422922), ('eer_agg_psnr', 0.26448871551964337), ('eer_agg_squared', 0.27979876160988776), ('eer_agg_ssim', 0.23802429520971827), ('eer_overall_absolute', 0.4368932038835619), ('eer_overall_psnr', 0.3756067961164692), ('eer_overall_squared', 0.3729281767955802), ('eer_overall_ssim', 0.3774271844653544), ('pr_roc_score_agg_absolute', 0.661

{'targets': array([array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0]),
        array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [4]:
exit()

In [5]:
test_model(
    dataset_type = "mv_tec",
    model = SoftMaxConvAttentionWrapper(C2D_AE_128_3x3(channels = 3)),
    model_path = '../../ATTN_PPR_MODELS/MV-TEC/C2D_AE_128_3X3-_SOFTMAX_ATTENTION_P64_C3_ADAM_MSE_MV_TEC_NORMAL-{APE}/C2D_AE_128_3X3-_SOFTMAX_ATTENTION_P64_C3_ADAM_MSE_MV_TEC_NORMAL-{APE}.pth.tar',
    tester_kwargs = {
        "save_vis": True,
        "regularity_type": "normalized_regularity",
        "stackFrames": 64,
        "recordResults": False,
        "forceNormalTest": False,
        "filename_addon": "dummy",
        "setEval": True, 
        "useGPU": True
    },
    dataset_kwargs={'image_size': 128, 'image_type': 'normal'},
    return_results=True
)

100%|██████████| 17/17 [00:47<00:00,  2.82s/it]
1it [00:00,  6.25it/s]

----------------------------------------


15it [00:02,  5.57it/s]

Per anomaly AUC-ROC scores: [0.88968254 0.70895802 0.53011568 0.38964687 0.70760234 0.74892857
 0.55842391 0.5542522  0.63829787 0.44353351 0.71789322 0.95555556
 0.71291667 0.88508772 0.75682773] | Mean AUC-ROC Score: 0.6798481602427754



/home/ambreesh/Documents/PROJECTS/THESIS_WORK/VideoAnomalyDetection/AutoEncoders/test_autoencoder.py:579: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  overall_results[param] = np.array(param_list)


{'targets': array([array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
        array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
        array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 1, 1, 

In [3]:
test_model(
    dataset_type = "avenue",
    model = SoftMaxConvAttentionWrapper(C2D_AE_128_3x3(channels = 3)),
    model_path = '../../ATTN_PPR_MODELS/AVENUE/C2D_AE_128_3X3-_SOFTMAX_ATTENTION_P64_C3_ADAM_MSE_AVENUE_NORMAL-{APE}/C2D_AE_128_3X3-_SOFTMAX_ATTENTION_P64_C3_ADAM_MSE_AVENUE_NORMAL-{APE}.pth.tar',
    tester_kwargs = {
        "save_vis": True,
        "regularity_type": "normalized_regularity",
        "stackFrames": 64,
        "recordResults": False,
        "forceNormalTest": False,
        "filename_addon": "dummy",
        "useGPU": True
    },
    dataset_kwargs={'image_size': 128, 'image_type': 'normal'},
    return_results=True
)

../general/data.py:709: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  temporal_labels = np.array(temporal_labels)
21it [01:25,  4.05s/it]


----------------------------------------


21it [02:14,  6.41s/it]
/home/ambreesh/Documents/amb_venv/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)


OrderedDict([('auc_roc_score_agg_absolute', 0.8443712120412349), ('auc_roc_score_agg_psnr', 0.8534799627820171), ('auc_roc_score_agg_squared', 0.8922992222570878), ('auc_roc_score_agg_ssim', 0.8101500072836348), ('auc_roc_score_mean_absolute', 0.8249719211262677), ('auc_roc_score_mean_psnr', 0.8351602177457383), ('auc_roc_score_mean_squared', 0.8351602177457383), ('auc_roc_score_mean_ssim', 0.8422033206032425), ('auc_roc_score_overall_absolute', 0.9456753066361869), ('auc_roc_score_overall_psnr', 0.9638883071407284), ('auc_roc_score_overall_squared', 0.9638883071407284), ('auc_roc_score_overall_ssim', 0.9425003986517941), ('eer_agg_absolute', 0.226058555931419), ('eer_agg_psnr', 0.20500666567960651), ('eer_agg_squared', 0.16003732649158203), ('eer_agg_ssim', 0.2573194914262918), ('eer_overall_absolute', 0.11159837841972413), ('eer_overall_psnr', 0.09168319141404785), ('eer_overall_squared', 0.09168319141466305), ('eer_overall_ssim', 0.12842541845652494), ('pr_roc_score_agg_absolute', 0

{'targets': array([array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]),
        array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1,

In [9]:
test_model(
    dataset_type = "ham10000",
    model = C2D_AE_128_3x3(channels = 3),
    model_path = '../../VAD_MODEL_TREE/HAM10000/C2D/C2D_AE_128_3X3|_ADAM_MSE_HAM10000_NORMAL/C2D_AE_128_3X3|_ADAM_MSE_HAM10000_NORMAL.pth.tar',
    tester_kwargs = {
        "save_vis": True,
        "regularity_type": "normalized_regularity",
        "stackFrames": 64,
        "recordResults": False,
        "useGPU": True
    },
    dataset_kwargs={'image_size': 128, 'image_type': 'normal'},
)

1it [00:00,  5.76it/s]

----------------------------------------


6it [00:00,  6.11it/s]

Per anomaly AUC-ROC scores: [0.8683 0.7973 0.771  0.632  0.8235 0.6669] | Mean AUC-ROC Score: 0.7598333333333334


True

In [10]:
test_model(
    dataset_type = "ham10000",
    model = ConvAttentionWrapper(C2D_AE_128_3x3(channels = 3)),
    model_path = '../../VAD_MODEL_TREE/HAM10000/C2D/C2D_AE_128_3X3|_CONV_ATTENTION_ADAM_MSE_HAM10000_NORMAL/C2D_AE_128_3X3|_CONV_ATTENTION_ADAM_MSE_HAM10000_NORMAL.pth.tar',
    tester_kwargs = {
        "save_vis": True,
        "regularity_type": "normalized_regularity",
        "stackFrames": 64,
        "recordResults": False,
        "useGPU": True
    },
    dataset_kwargs={'image_size': 128, 'image_type': 'normal'},
)

0it [00:00, ?it/s]

----------------------------------------


6it [00:01,  3.89it/s]

Per anomaly AUC-ROC scores: [0.8084 0.6718 0.6602 0.6503 0.7556 0.5893] | Mean AUC-ROC Score: 0.6892666666666667


True

In [7]:
test_model(
    dataset_type = "ucsd2",
    model = CGRU_AE(channels = 1),
    model_path = '../../VAD_MODEL_TREE/UCSD2/CLSTM/CLSTM_30_01_2021_17_35/CGRU_AE_128_3X3_L-4_RL-2_DISDECONV-Y|_ADAM_MSE_UCSD2_NORMAL/CGRU_AE_128_3X3_L-4_RL-2_DISDECONV-Y|_ADAM_MSE_UCSD2_NORMAL.pth.tar',
    tester_kwargs = {
        "save_vis": False,
        "recordResults": False,
        "setEval": False,
        "useGPU": True
    },
    dataset_kwargs={'image_size': 128, 'image_type': 'normal'},
)

../general/data.py:406: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  temporal_labels = np.array(temporal_labels)
12it [00:01,  7.21it/s]
0it [00:00, ?it/s]

----------------------------------------


12it [00:10,  1.11it/s]

OrderedDict([('auc_roc_score_agg_absolute', 0.8413094056750523), ('auc_roc_score_agg_psnr', 0.8523926540792792), ('auc_roc_score_agg_squared', 0.8621969371882208), ('auc_roc_score_agg_ssim', 0.8273581236925387), ('auc_roc_score_mean_absolute', 0.8959183289033936), ('auc_roc_score_mean_psnr', 0.8878420961890183), ('auc_roc_score_mean_squared', 0.8857108853455187), ('auc_roc_score_mean_ssim', 0.8995361876561072), ('auc_roc_score_overall_absolute', 0.6943624953065495), ('auc_roc_score_overall_psnr', 0.702185471758837), ('auc_roc_score_overall_squared', 0.700386874430081), ('auc_roc_score_overall_ssim', 0.7128044037976722), ('eer_agg_absolute', 0.19660194174858747), ('eer_agg_psnr', 0.1958393113342902), ('eer_agg_squared', 0.20441988950276258), ('eer_agg_ssim', 0.2524271844647128), ('eer_overall_absolute', 0.4419889502762431), ('eer_overall_psnr', 0.4309392265192693), ('eer_overall_squared', 0.42900485437000774), ('eer_overall_ssim', 0.4194708081679609), ('pr_roc_score_agg_absolute', 0.687


/home/ambreesh/Documents/amb_venv/lib/python3.6/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
/home/ambreesh/Documents/amb_venv/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/ambreesh/Documents/amb_venv/lib/python3.6/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to contr

In [4]:
exit()